# Generated by Django 5.2 on 2025-04-25 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.EmailField(max_length=255, unique=True)),
                ('course_description', models.TextField(verbose_name=())),
                ('course_time', models.CharField(max_length=50)),
                ('class_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_time', models.CharField(max_length=50)),
                ('lesson_week', models.CharField(max_length=50)),
                ('lesson_brief', models.TextField(verbose_name=())),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.schedule'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=255, unique=True)),
                ('user_pass', models.CharField(max_length=50)),
                ('user_Fname', models.CharField(max_length=255)),
                ('user_Lname', models.CharField(max_length=255)),
                ('is_teacher', models.BooleanField(default=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='is_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user'),
        ),
    ]
