# Generated by Django 5.2 on 2025-04-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_course_course_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='class_id',
            new_name='course_id',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_brief',
            field=models.TextField(),
        ),
    ]
