# Generated by Django 5.2 on 2025-04-25 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_class_id_user_course_id_lesson_lesson_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='course_id',
            new_name='course_related',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='schedule_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lesson_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='course_id',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_sch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main_app.schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='enrolled_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=50),
        ),
    ]
